---
- name: CHECK IF WP-CLI INSTALLED
  stat: path=/usr/local/bin/wp-cli
  register: wp_installed

- name: DOWNLOAD wp-cli.phar
  get_url:
    url: "{{ wp }}"
    mode: '0755'
    dest: "{{ path }}"
  when: not wp_installed.stat.exists

- debug:
    msg: "WP-CLI IS ALREADY INSTALLED, SKIPPPING"
  when: wp_installed.stat.exists
