---
- set_fact: path_to_pool="{{ pool }}/{{ domain }}"

- name: BUILD DIRECTORIES
  name: "{{ item }}"
  loop: "{{ create_dirs }}"
  file: 
    path: "{{ item }}"
    state: directory

- name: ADD TEMPLATE OF SNIPPETS
  template:
    src: fastcgi-php.conf
    dest: "{{ snippets }}"

- name: ADD TEMPLATE TO POOL.D
  template:
    src: default.conf
    dest: "{{ pool }}"

- name: ADD TEMPLATE OF FASTCGI.CONF
  template:
    src: fastcgi.conf
    dest: /etc/nginx

- name: GIVE NAME TO CONFIG FILE
  command: mv "{{ pool }}"/default.conf "{{ path_to_pool }}".conf

- name: RESTART PHP
  service:
    name: php7.3-fpm
    state: restarted
