---
service: mysql
path: /root
auth_change: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
flush: mysql -u root -e 'FLUSH PRIVILEGES'
packages: 
  - mysql-client
  - mysql-common
  - mysql-server
  - python-mysqldb
