---
- set_fact: path_to_conf="{{ available }}/{{ domain }}"

- set_fact: path_to_sym="{{ enabled }}/{{ domain }}"

- name: BUILD /OPT/DOMAINS/{{ DOMAIN }} AND /ETC/NGINX/SITES-* DIRECTORIES 
  name: "{{ item }}"
  loop: "{{ create_dirs }}"
  file: 
    path: "{{ item }}"
    state: directory

- name: ADD NGINX.CONF
  template:
    src: nginx.conf
    dest: /etc/nginx

- name: STOP APACHE2
  service:
    name: apache2
    state: stopped

- name: START NGINX
  service:
    name: nginx
    state: started

- name: ADD TEMPLATE TO /ETC/NGINX/SITES-AVAILABLE
  template:
    src: default.conf
    dest: "{{ available }}"

- name: RENAME TEMPLATE
  command: mv "{{ available }}"/default.conf "{{ path_to_conf }}" 

- name: CREATE SYMLINK BETWEEN /ETC/NGINX/SITES-*
  file:
    src: "{{ path_to_conf }}"
    dest: "{{ path_to_sym }}"
    state: link
    force: yes

- name: PASTE TEST JPEG
  loop:
    - test.jpeg
    - index.php
  copy:
    src: "{{ item }}"
    dest: "{{ domains }}"
    mode: "0755"
