---
- name: CHECK IF NGINX IS ALREADY INSTALLED (SKIPPING INSTALLATION IF IT IS INSTALLED)
  stat: path=/etc/nginx/
  register: nginx_dir

- block:
  - name: IMPORT KEY FOR NGINX REPOSITORY
    shell: "{{ add_key }}"

  - name: INSTALL NGINX REPOSITORY
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
      force: yes
    loop: "{{ packages }}"

  - name: ACTIVATE NGINX APT REPOSITORY
    shell: echo "{{ instal_repo }}" >> "{{ repo_directory }}"

  - name: INSTALL NGINX
    apt:
      name: "{{ service }}"
      state: latest  
  when: not nginx_dir.stat.exists

- debug:
    msg: "NGINX IS ALREADY INSTALLED, ABORTING"
  when: nginx_dir.stat.exists
